(() => {
  const data = window.DUSTY_MOCK;
  const $ = s => document.querySelector(s);
  const money = v => Number(v).toLocaleString(undefined,{style:"currency",currency:"USD"});
  const pct = v => `${v>=0?"+":""}${Number(v).toFixed(2)}%`;
  const metric = (l,v,n="") => `<div class="metric"><label>${l}</label><strong>${v}</strong><small>${n}</small></div>`;
  const kv = (l,v) => `<div class="kv"><span>${l}</span><span>${v}</span></div>`;
  let pendingCommand=null;

  $("#serviceStrip").innerHTML=data.services.map(([n,s])=>`<span class="service-pill"><b>${n}</b> <span class="state-${s}">● ${s}</span></span>`).join("");
  $("#firmMetrics").innerHTML=[metric("FIRM EQUITY",money(data.firm.equity),`${money(data.firm.pnl24h)} / 24H`),metric("MTD GROWTH",pct(data.firm.pnlMonthPct),`${data.firm.monthlyTargetPct.toFixed(1)}% objective`),metric("DRAWDOWN",`${data.firm.drawdownPct.toFixed(2)}%`,"NORMAL"),metric("OPEN RISK",`${data.firm.openRiskPct.toFixed(2)}%`,"CAUTION: USD cluster"),metric("FREE MARGIN",money(data.firm.freeMargin),"analytical aggregate"),metric("EXECUTION","READY 5/6","G06 fault-latched")].join("");
  $("#firmTicker").innerHTML=[...data.ticker,...data.ticker].map(x=>`<span>${x}</span>`).join("");
  $("#incidentList").innerHTML=data.incidents.map(x=>`<div class="incident"><span class="severity ${x.severity}">${x.severity}</span> <b>${x.title}</b><p>${x.detail}</p></div>`).join("");
  $("#timeline").innerHTML=data.overnight.map(([t,e])=>`<div class="timeline-row"><time>${t}</time><span>${e}</span></div>`).join("");
  $("#researchDelta").innerHTML=[kv("Jobs completed",data.research.completed),kv("Candidates promoted",data.research.promoted),kv("Candidates rejected",data.research.rejected),kv("Holdout",`${data.research.holdoutPass}/${data.research.holdoutTotal} PASS`),kv("Challenge",`Day ${data.research.challengeDay}/${data.research.challengeLength}`)].join("");
  $("#rejectedSummary").innerHTML=[kv("Total rejected",data.rejected.total),kv("Portfolio capacity",data.rejected.portfolioCapacity),kv("Desk risk",data.rejected.deskRisk),kv("Correlation",data.rejected.correlation),kv("Avoided loss",money(data.rejected.avoidedLoss)),kv("Missed profit",money(data.rejected.missedProfit)),kv("Governance value",money(data.rejected.avoidedLoss-data.rejected.missedProfit))].join("");
  $("#deskMatrix").innerHTML=data.desks.map(d=>`<div class="desk-tile" data-matrix-desk="${d.id}"><b>${d.id}</b> <span class="state-${d.state}">● ${d.state}</span><small>${d.state==="FAULT"?"EXECUTION BLOCKED":`Equity ${money(d.equity)}`}</small><div class="numbers"><span>MTD ${pct(d.mtd)}</span><span>DD ${d.dd.toFixed(2)}%</span><span>PF ${d.pf.toFixed(2)}</span><span>Risk ${d.risk.toFixed(2)}%</span></div></div>`).join("");

  const canvas=$("#orbitalCanvas"); const viewport=$("#tradingFloorViewport"); const ctx=canvas.getContext("2d");
  let dpr=Math.min(window.devicePixelRatio||1,2), W=1,H=1;
  let rotationY=-0.25, rotationX=0.18, dragging=false,dragMoved=false,lastX=0,lastY=0;
  let focusDesk=null, transition=null, hoverNode=null, hitNodes=[];
  let lastFrame=performance.now();
  const orbitBaseSpeeds=[0.014,0.011,0.009,0.012,0.0085,0.0105];
  const phases=[0,Math.PI*.34,Math.PI*.71,Math.PI,Math.PI*1.35,Math.PI*1.72];
  const radii=[225,205,240,190,230,210];
  const inclinations=[0.22,-0.38,0.52,-0.18,0.35,-0.48];
  const deskSystems=data.deskSystems||["POSITIONS","RISK","RESEARCH","EXECUTION","GRADUATION","KNOWLEDGE"];

  function resize(){const r=canvas.getBoundingClientRect();W=Math.max(1,r.width);H=Math.max(1,r.height);canvas.width=W*dpr;canvas.height=H*dpr;ctx.setTransform(dpr,0,0,dpr,0,0)}
  new ResizeObserver(resize).observe(canvas); resize();
  function rotatePoint(x,y,z){let cy=Math.cos(rotationY),sy=Math.sin(rotationY);let x1=x*cy+z*sy,z1=-x*sy+z*cy;let cx=Math.cos(rotationX),sx=Math.sin(rotationX);let y1=y*cx-z1*sx,z2=y*sx+z1*cx;return{x:x1,y:y1,z:z2}}
  function project(p){const camera=720,scale=camera/(camera-p.z);return{x:W/2+p.x*scale,y:H/2+p.y*scale,scale,z:p.z}}
  function nodeColor(state){if(state==="FAULT")return{edge:"#ff6175",glow:"rgba(255,97,117,.55)"};if(state==="CAUTION")return{edge:"#ffc568",glow:"rgba(255,197,104,.5)"};return{edge:"#67d7ff",glow:"rgba(103,215,255,.45)"}}
  function drawOrbit(radius,inc){ctx.save();ctx.strokeStyle="rgba(103,215,255,.10)";ctx.lineWidth=1;ctx.beginPath();for(let i=0;i<=120;i++){let a=i/120*Math.PI*2,x=Math.cos(a)*radius,z=Math.sin(a)*radius,y=Math.sin(a)*radius*Math.sin(inc)*.55;let p=project(rotatePoint(x,y,z));if(i===0)ctx.moveTo(p.x,p.y);else ctx.lineTo(p.x,p.y)}ctx.stroke();ctx.restore()}
  function drawNode(n){const c=nodeColor(n.state);ctx.save();ctx.shadowColor=c.glow;ctx.shadowBlur=n.hover?28:16;let g=ctx.createRadialGradient(n.x-n.r*.28,n.y-n.r*.3,3,n.x,n.y,n.r);g.addColorStop(0,"rgba(106,225,255,.95)");g.addColorStop(.2,"rgba(24,93,120,.95)");g.addColorStop(1,"rgba(3,14,20,.98)");ctx.fillStyle=g;ctx.strokeStyle=c.edge;ctx.lineWidth=n.center?1.8:1.2;ctx.beginPath();ctx.arc(n.x,n.y,n.r,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.shadowBlur=0;ctx.textAlign="center";ctx.textBaseline="middle";ctx.fillStyle="#d7f2ff";ctx.font=`${n.center?"600 15px":"600 10px"} Segoe UI`;ctx.fillText(n.label,n.x,n.y-3);ctx.fillStyle=n.state==="NORMAL"?"#65f2b0":c.edge;ctx.font="8px Segoe UI";ctx.fillText(n.sub||n.state,n.x,n.y+12);ctx.restore()}
  function renderOrbit(now){const dt=Math.min(50,now-lastFrame);lastFrame=now;ctx.clearRect(0,0,W,H);hitNodes=[];let levelNodes;
    if(!focusDesk){[190,210,230].forEach((r,i)=>drawOrbit(r,[.22,-.38,.48][i]));levelNodes=data.desks.map((d,i)=>{let a=phases[i]+now*orbitBaseSpeeds[i]*0.001;let r=radii[i],inc=inclinations[i];let x=Math.cos(a)*r,z=Math.sin(a)*r,y=Math.sin(a)*r*Math.sin(inc)*.72;let p=project(rotatePoint(x,y,z));return{kind:"desk",id:d.id,label:d.id,state:d.state,sub:d.state,x:p.x,y:p.y,z:p.z,r:Math.max(23,33*p.scale)}})}
    else{[175,205,235].forEach((r,i)=>drawOrbit(r,[.35,-.25,.5][i]));levelNodes=deskSystems.map((name,i)=>{let a=phases[i]+now*(0.0065+i*.0004)*0.001;let r=[180,205,230,190,220,200][i],inc=[.25,-.32,.42,-.2,.34,-.46][i];let x=Math.cos(a)*r,z=Math.sin(a)*r,y=Math.sin(a)*r*Math.sin(inc)*.65;let p=project(rotatePoint(x,y,z));return{kind:"system",id:name,label:name,state:focusDesk.state,sub:name==="RISK"?`${focusDesk.risk.toFixed(2)}%`:name==="GRADUATION"?`${focusDesk.progress}%`:"ACTIVE",x:p.x,y:p.y,z:p.z,r:Math.max(22,31*p.scale)}})}
    levelNodes.sort((a,b)=>a.z-b.z).forEach(n=>{n.hover=hoverNode&&hoverNode.kind===n.kind&&hoverNode.id===n.id;drawNode(n);hitNodes.push(n)});
    let center={kind:"center",id:focusDesk?focusDesk.id:"FIRM",label:focusDesk?focusDesk.id:"DUSTY CORE",state:focusDesk?focusDesk.state:"NORMAL",sub:focusDesk?focusDesk.graduation:"OPERATIONAL",x:W/2,y:H/2,z:999,r:58,center:true};center.hover=hoverNode&&hoverNode.kind==="center";drawNode(center);hitNodes.push(center);
    requestAnimationFrame(renderOrbit)}
  requestAnimationFrame(renderOrbit);

  function hitAt(x,y){return [...hitNodes].reverse().find(n=>Math.hypot(x-n.x,y-n.y)<=n.r)}
  canvas.addEventListener("pointerdown",e=>{if($("#floorDetail").hidden===false)return;dragging=true;dragMoved=false;lastX=e.clientX;lastY=e.clientY;viewport.classList.add("dragging");canvas.setPointerCapture(e.pointerId)});
  canvas.addEventListener("pointermove",e=>{let r=canvas.getBoundingClientRect(),x=e.clientX-r.left,y=e.clientY-r.top;hoverNode=hitAt(x,y)||null;if(dragging){let dx=e.clientX-lastX,dy=e.clientY-lastY;if(Math.abs(dx)+Math.abs(dy)>2)dragMoved=true;rotationY+=dx*.008;rotationX=Math.max(-.72,Math.min(.72,rotationX+dy*.005));lastX=e.clientX;lastY=e.clientY}});
  canvas.addEventListener("pointerup",e=>{viewport.classList.remove("dragging");if(!dragMoved){let r=canvas.getBoundingClientRect(),n=hitAt(e.clientX-r.left,e.clientY-r.top);if(n){if(n.kind==="desk")descend(n.id);else if(n.kind==="center")openDetails()}}dragging=false});
  canvas.addEventListener("pointerleave",()=>{hoverNode=null});

  function updateDossier(){if(!focusDesk){$("#deskDossier").innerHTML=[metric("FIRM",data.firm.state,"click center for firm detail"),metric("DESKS","6 GENERALIST","slow 3D orbital system"),metric("PORTFOLIO",pct(data.firm.pnlMonthPct),"MTD growth"),metric("RISK",`${data.firm.openRiskPct.toFixed(2)}%`,"open risk")].join("");$("#focusLabel").textContent="FIRM / GENERALIST LAYER";$("#backToFirm").hidden=true}else{$("#deskDossier").innerHTML=[metric("EQUITY",money(focusDesk.equity),"independent desk capital"),metric("TODAY",pct(focusDesk.today),"realized + floating"),metric("MTD",pct(focusDesk.mtd),`PF ${focusDesk.pf.toFixed(2)} · Sharpe ${focusDesk.sharpe.toFixed(2)}`),metric("RISK / DD",`${focusDesk.risk.toFixed(2)}% / ${focusDesk.dd.toFixed(2)}%`,focusDesk.state)].join("");$("#focusLabel").textContent=`${focusDesk.id} / DESK SYSTEM`;$("#backToFirm").hidden=false}}
  function descend(id){const d=data.desks.find(x=>x.id===id);if(!d)return;canvas.animate([{transform:"scale(1)",opacity:1},{transform:"scale(1.75)",opacity:.15}],{duration:480,easing:"cubic-bezier(.2,.75,.25,1)"}).onfinish=()=>{focusDesk=d;rotationY=-.18;rotationX=.12;updateDossier();canvas.animate([{transform:"scale(.72)",opacity:.08},{transform:"scale(1)",opacity:1}],{duration:620,easing:"cubic-bezier(.2,.75,.25,1)"})}}
  $("#backToFirm").addEventListener("click",()=>{focusDesk=null;rotationY=-.25;rotationX=.18;updateDossier()});
  $("#closeDetail").addEventListener("click",()=>{$("#floorDetail").hidden=true});

  function curveBars(seed){return Array.from({length:22},(_,i)=>{let v=24+((i*17+seed*13)%61);return `<span style="height:${v}%"></span>`}).join("")}
  function detailStats(d){return [["Balance",money(d?d.equity+37.42:data.firm.balance)],["Equity",money(d?d.equity:data.firm.equity)],["Return Today",d?pct(d.today):pct(.62)],["This Week",d?pct(d.mtd*.42):pct(data.firm.pnlWeekPct)],["This Month",d?pct(d.mtd):pct(data.firm.pnlMonthPct)],["Profit Factor",d?d.pf.toFixed(2):"1.71"],["Sharpe",d?d.sharpe.toFixed(2):"1.36"],["Sortino",d?(d.sharpe*1.38).toFixed(2):"1.88"],["Drawdown",d?`${d.dd.toFixed(2)}%`:`${data.firm.drawdownPct.toFixed(2)}%`],["Expectancy",d?`+${(.14+d.pf*.07).toFixed(2)}R`:"+0.27R"],["Win Rate",d?`${(51+d.pf*6).toFixed(1)}%`:"61.6%"],["Open Risk",d?`${d.risk.toFixed(2)}%`:`${data.firm.openRiskPct.toFixed(2)}%`]]}
  function openDetails(){const d=focusDesk;$("#detailIdentity").textContent=d?`${d.id} / ACCOUNT PERFORMANCE`:`DUSTY DRAGON / FIRM PERFORMANCE`;const recent=data.positions.filter(p=>!d||p.desk===d.id);const stats=detailStats(d);$("#detailContent").innerHTML=`<div class="account-hero"><section class="account-identity"><h2>${d?d.id:"Dusty Dragon"}</h2><p>Type: ${d?"Generalist Desk":"Firm Aggregate"}</p><p>Environment: ${d&&d.id==="G06"?"DEMO / BLOCKED":"DEMO / UI LAB"}</p><p>State: <b class="state-${d?d.state:"NORMAL"}">${d?d.state:data.firm.state}</b></p><p>Graduation: ${d?d.graduation:"—"}</p><p>Progress: ${d?d.progress+"%":"Layer view"}</p></section><section class="account-performance"><table><thead><tr><th>Performance</th><th>Return</th><th>Profit</th><th>Trades</th></tr></thead><tbody><tr><td>Today</td><td>${d?pct(d.today):pct(.62)}</td><td>${money(d?d.today*d.equity/100:169.4)}</td><td>${d?"3":"12"}</td></tr><tr><td>This Week</td><td>${d?pct(d.mtd*.42):pct(data.firm.pnlWeekPct)}</td><td>${money(d?d.equity*d.mtd*.0042:497.2)}</td><td>${d?"14":"54"}</td></tr><tr><td>This Month</td><td>${d?pct(d.mtd):pct(data.firm.pnlMonthPct)}</td><td>${money(d?d.equity*d.mtd/100:1034.6)}</td><td>${d?"31":"138"}</td></tr><tr><td>All Time</td><td>${d?pct(d.mtd*2.7):"+12.84%"}</td><td>${money(d?d.equity*.118:3297.04)}</td><td>${d?"117":"391"}</td></tr></tbody></table></section><section class="account-curves"><small>RETURN BY TRADE</small><div class="mini-curve">${curveBars(d?Number(d.id.slice(1)):7)}</div><small>BALANCE / EQUITY PATH</small></section></div><div class="detail-grid"><section class="detail-panel"><h3>QUANT STATISTICS</h3><div class="stat-cloud">${stats.map(([a,b])=>`<div><span>${a}</span><b>${b}</b></div>`).join("")}</div></section><section class="detail-panel"><h3>RECENT / OPEN TRADES</h3><table class="detail-table"><thead><tr><th>Symbol</th><th>Side</th><th>P&L</th><th>R</th></tr></thead><tbody>${(recent.length?recent:data.positions.slice(0,4)).map(p=>`<tr><td>${p.symbol}</td><td>${p.side}</td><td class="${p.pnl>=0?"positive":"negative"}">${money(p.pnl)}</td><td>${p.r.toFixed(2)}R</td></tr>`).join("")}</tbody></table></section><section class="detail-panel"><h3>RISK / EXECUTION / DEVELOPMENT</h3>${kv("Desk state",d?d.state:data.firm.state)}${kv("Graduation",d?d.graduation:"Firm")}${kv("Open risk",d?`${d.risk.toFixed(2)}%`:`${data.firm.openRiskPct}%`)}${kv("Max drawdown",d?`${d.dd.toFixed(2)}%`:`${data.firm.drawdownPct}%`)}${kv("Session",d&&d.id==="G06"?"FAULT-LATCHED":"VERIFIED")}${kv("Execution",d&&d.id==="G06"?"BLOCKED":"READY")}</section></div>`;$("#floorDetail").hidden=false}
  updateDossier();

  $("#watchlistTable").innerHTML=`<table class="data-table"><thead><tr><th>Symbol</th><th>Last</th><th>Move</th><th>Spread</th><th>Regime</th></tr></thead><tbody>${data.watchlist.map(x=>`<tr><td><b>${x.symbol}</b></td><td>${x.price}</td><td class="${x.move>=0?"positive":"negative"}">${pct(x.move)}</td><td>${x.spread}</td><td>${x.regime}</td></tr>`).join("")}</tbody></table>`;
  $("#decisionFeed").innerHTML=data.decisions.map(x=>`<div class="decision-item"><b><span>${x.time} · ${x.desk} · ${x.symbol}</span><span>${x.result}</span></b><p>Evidence score ${x.score}/100 · ${x.reason}</p></div>`).join("");
  $("#positionsTable").innerHTML=`<table class="data-table"><thead><tr><th>Desk / Symbol</th><th>Side</th><th>Entry</th><th>Mark</th><th>P&L</th><th>R</th><th>Risk</th><th>Age</th></tr></thead><tbody>${data.positions.map(x=>`<tr><td>${x.desk} · <b>${x.symbol}</b></td><td>${x.side}</td><td>${x.entry}</td><td>${x.mark}</td><td class="${x.pnl>=0?"positive":"negative"}">${money(x.pnl)}</td><td>${x.r.toFixed(2)}R</td><td>${x.risk.toFixed(2)}%</td><td>${x.age}</td></tr>`).join("")}</tbody></table>`;
  const heatClass=v=>v>.25?"positive-risk":v<-.25?"negative-risk":"neutral-risk";
  $("#riskHeatmap").innerHTML=data.riskHeatmap.map(x=>`<div class="heat-tile ${heatClass(x.value)}" style="grid-column:span ${Math.max(2,Math.round(x.size/3.2))};grid-row:span ${Math.max(2,Math.round(x.size/5))}" title="${x.label}: ${x.risk}% risk contribution"><small>${x.label}</small><strong>${x.symbol}</strong><span>${pct(x.value)}</span><small>RISK ${x.risk}%</small></div>`).join("");
  $("#riskStats").innerHTML=[kv("Portfolio open risk",`${data.riskStats.portfolioOpenRisk}%`),kv("Gross exposure",`${data.riskStats.grossExposure}%`),kv("Net exposure",`${data.riskStats.netExposure}%`),kv("USD contribution",`${data.riskStats.usdContribution}%`),kv("Max pair correlation",data.riskStats.maxPairCorrelation),kv("Simultaneous loss freq",`${data.riskStats.simultaneousLossFreq}%`),kv("VaR 95",`${data.riskStats.var95}%`),kv("Expected shortfall",`${data.riskStats.expectedShortfall}%`)].join("");
  const corr=[1,.44,.31,.18,.52,.22,.44,1,.28,.36,.81,.19,.31,.28,1,.41,.24,.33,.18,.36,.41,1,.37,.29,.52,.81,.24,.37,1,.43,.22,.19,.33,.29,.43,1];$("#correlationMatrix").innerHTML=corr.map(v=>`<div class="corr-cell" style="--a:${(.08+v*.42).toFixed(2)}">${v.toFixed(2)}</div>`).join("");
  $("#performanceStats").innerHTML=data.performance.stats.map(([l,v])=>`<div class="stat-block"><span>${l}</span><b>${v}</b></div>`).join("");$("#equityBars").innerHTML=data.performance.returns.map(v=>`<div class="equity-bar" style="height:${20+v*18}%"><span>${v.toFixed(1)}%</span></div>`).join("");$("#deskAttribution").innerHTML=data.performance.deskAttribution.map(x=>`<div class="attrib-row"><div class="attrib-head"><b>${x.id}</b><span>${money(x.pnl)} · ${x.pct}%</span></div><div class="bar-track"><div class="bar-fill" style="width:${x.pct*2.7}%"></div></div></div>`).join("");
  $("#researchQueue").innerHTML=data.researchQueue.map(x=>`<div class="research-item"><header><b>${x.id} · ${x.title}</b><span>${x.stage}</span></header><p>Impact ${x.impact} · ${x.progress}% complete</p><div class="progress"><span style="width:${x.progress}%"></span></div></div>`).join("");$("#evidenceList").innerHTML=data.evidence.map(x=>`<div class="evidence-item"><header><b>${x.state}</b><span>${x.confidence}% confidence</span></header><p>${x.claim}</p><small>${x.age} old</small></div>`).join("");$("#researchStats").innerHTML=[kv("Completed",data.research.completed),kv("Active",data.research.active),kv("Promoted",data.research.promoted),kv("Rejected",data.research.rejected),kv("Holdout",`${data.research.holdoutPass}/${data.research.holdoutTotal}`)].join("");
  const c=data.challenge;$("#challengeScore").innerHTML=`<div class="challenge-card"><h3>${c.target}</h3><div class="challenge-cols"><div><b>INCUMBENT</b>${kv("Return",pct(c.incumbent.ret))}${kv("DD",`${c.incumbent.dd}%`)}${kv("PF",c.incumbent.pf)}${kv("Sharpe",c.incumbent.sharpe)}</div><div><b>CHALLENGER</b>${kv("Return",pct(c.challenger.ret))}${kv("DD",`${c.challenger.dd}%`)}${kv("PF",c.challenger.pf)}${kv("Sharpe",c.challenger.sharpe)}</div></div><p>Day ${c.day}/${c.length} · Verdict: <b>${c.verdict}</b></p></div>`;
  $("#systemRows").innerHTML=`<div class="system-row head"><span>Component</span><span>State</span><span>Latency</span><span>CPU</span><span>RAM</span></div>${data.systems.map(x=>`<div class="system-row"><b>${x.name}</b><span class="state-${x.state}">${x.state}</span><span>${x.latency}</span><span>${x.cpu}%</span><span>${x.ram} MB</span></div>`).join("")}`;$("#auditRows").innerHTML=data.audit.map(([t,e,l])=>`<div class="audit-row"><time>${t}</time><span>${e}</span><span>${l}</span></div>`).join("");

  document.addEventListener("click",e=>{const m=e.target.closest("[data-matrix-desk]");if(m)descend(m.dataset.matrixDesk);const w=e.target.closest("[data-workspace]");if(w){document.querySelectorAll("[data-workspace]").forEach(b=>b.classList.toggle("active",b===w));document.querySelectorAll(".workspace").forEach(s=>s.classList.toggle("active",s.id===w.dataset.workspace))}const cmd=e.target.closest("[data-command]");if(cmd){pendingCommand=cmd.dataset.command;$("#dialogTitle").textContent=pendingCommand.replaceAll("_"," ");$("#dialogCopy").textContent="UI laboratory only. Confirming records a local mock audit event; no MT5 or broker path is touched.";$("#commandDialog").showModal()}});
  $("#confirmCommand").addEventListener("click",()=>{if(pendingCommand)$("#auditTail").textContent=`Audit: ${pendingCommand} mock-confirmed at ${new Date().toLocaleTimeString()}`;pendingCommand=null});
  function setMode(m){const a=m==="analytical";document.body.classList.toggle("analytical-mode",a);document.body.classList.toggle("spatial-mode",!a);$("#modeButton").textContent=a?"F3 SPATIAL":"F2 ANALYTICAL"}$("#modeButton").addEventListener("click",()=>setMode(document.body.classList.contains("analytical-mode")?"spatial":"analytical"));window.addEventListener("keydown",e=>{if(e.key==="F2"){e.preventDefault();setMode("analytical")}if(e.key==="F3"){e.preventDefault();setMode("spatial")}});
  function clock(){$("#clock").textContent=new Intl.DateTimeFormat("en-US",{hour:"2-digit",minute:"2-digit",second:"2-digit",hour12:false}).format(new Date())+" LOCAL"}clock();setInterval(clock,1000);
})();