(() => {
  const data = window.DUSTY_MOCK;
  const hierarchy = data.hierarchy;
  const $ = s => document.querySelector(s);
  const money = v => Number(v || 0).toLocaleString(undefined,{style:"currency",currency:"USD"});
  const pct = v => `${Number(v)>=0?"+":""}${Number(v||0).toFixed(2)}%`;
  const metric = (l,v,n="") => `<div class="metric"><label>${l}</label><strong>${v}</strong><small>${n}</small></div>`;
  const kv = (l,v) => `<div class="kv"><span>${l}</span><span>${v}</span></div>`;
  let pendingCommand = null;

  $("#serviceStrip").innerHTML=data.services.map(([n,s])=>`<span class="service-pill"><b>${n}</b> <span class="state-${s}">● ${s}</span></span>`).join("");
  $("#firmMetrics").innerHTML=[metric("FIRM EQUITY",money(data.firm.equity),`${money(data.firm.pnl24h)} / 24H`),metric("MTD GROWTH",pct(data.firm.pnlMonthPct),`${data.firm.monthlyTargetPct.toFixed(1)}% objective`),metric("DRAWDOWN",`${data.firm.drawdownPct.toFixed(2)}%`,"NORMAL"),metric("OPEN RISK",`${data.firm.openRiskPct.toFixed(2)}%`,"CAUTION: USD cluster"),metric("FREE MARGIN",money(data.firm.freeMargin),"analytical aggregate"),metric("EXECUTION","READY 5/6","G06 fault-latched")].join("");
  $("#firmTicker").innerHTML=[...data.ticker,...data.ticker].map(x=>`<span>${x}</span>`).join("");
  $("#incidentList").innerHTML=data.incidents.map(x=>`<div class="incident"><span class="severity ${x.severity}">${x.severity}</span> <b>${x.title}</b><p>${x.detail}</p></div>`).join("");
  $("#timeline").innerHTML=data.overnight.map(([t,e])=>`<div class="timeline-row"><time>${t}</time><span>${e}</span></div>`).join("");
  $("#researchDelta").innerHTML=[kv("Jobs completed",data.research.completed),kv("Candidates promoted",data.research.promoted),kv("Candidates rejected",data.research.rejected),kv("Holdout",`${data.research.holdoutPass}/${data.research.holdoutTotal} PASS`),kv("Challenge",`Day ${data.research.challengeDay}/${data.research.challengeLength}`)].join("");
  $("#rejectedSummary").innerHTML=[kv("Total rejected",data.rejected.total),kv("Portfolio capacity",data.rejected.portfolioCapacity),kv("Desk risk",data.rejected.deskRisk),kv("Correlation",data.rejected.correlation),kv("Avoided loss",money(data.rejected.avoidedLoss)),kv("Missed profit",money(data.rejected.missedProfit)),kv("Governance value",money(data.rejected.avoidedLoss-data.rejected.missedProfit))].join("");
  $("#deskMatrix").innerHTML=data.desks.map(d=>`<div class="desk-tile" data-matrix-desk="${d.id}"><b>${d.id}</b> <span class="state-${d.state}">● ${d.state}</span><small>${d.state==="FAULT"?"EXECUTION BLOCKED":`${d.broker} · ${d.accountType}`}</small><div class="numbers"><span>MTD ${pct(d.mtd)}</span><span>DD ${d.dd.toFixed(2)}%</span><span>PF ${d.pf.toFixed(2)}</span><span>Risk ${d.risk.toFixed(2)}%</span></div></div>`).join("");

  const canvas=$("#orbitalCanvas"); const viewport=$("#tradingFloorViewport"); const ctx=canvas.getContext("2d");
  let dpr=Math.min(window.devicePixelRatio||1,2),W=1,H=1;
  let rotationY=-0.12,rotationX=0.10,dragging=false,dragMoved=false,lastX=0,lastY=0;
  let activeLayer=1,centerEntity={kind:"firm",id:"FIRM",name:"Dusty Core",state:"NORMAL"},hoverNode=null,hitNodes=[];
  const phases=[0,Math.PI*.34,Math.PI*.71,Math.PI,Math.PI*1.35,Math.PI*1.72];
  const orbitSpeeds=[0.0038,0.0033,0.0029,0.0035,0.0027,0.0031];
  const radii=[210,195,225,185,215,202];
  const inclinations=[0.32,-0.42,0.55,-0.26,0.39,-0.50];

  const byId=id=>hierarchy.nodes.find(n=>n.id===id);
  const layerById=id=>hierarchy.layers.find(l=>l.id===id);
  const childrenOf=id=>hierarchy.nodes.filter(n=>n.parentId===id);

  function resize(){const r=canvas.getBoundingClientRect();W=Math.max(1,r.width);H=Math.max(1,r.height);canvas.width=W*dpr;canvas.height=H*dpr;ctx.setTransform(dpr,0,0,dpr,0,0)}
  new ResizeObserver(resize).observe(canvas);resize();
  function rotatePoint(x,y,z){const cy=Math.cos(rotationY),sy=Math.sin(rotationY);const x1=x*cy+z*sy,z1=-x*sy+z*cy;const cx=Math.cos(rotationX),sx=Math.sin(rotationX);return{x:x1,y:y*cx-z1*sx,z:y*sx+z1*cx}}
  function project(p){const camera=820,scale=camera/(camera-p.z);return{x:W/2+p.x*scale,y:H/2+p.y*scale,scale,z:p.z}}
  function colorFor(state){if(state==="FAULT")return{edge:"#ff6175",glow:"rgba(255,97,117,.54)"};if(state==="CAUTION")return{edge:"#ffc568",glow:"rgba(255,197,104,.48)"};return{edge:"#67d7ff",glow:"rgba(103,215,255,.42)"}}
  function drawOrbit(radius,inc){ctx.save();ctx.strokeStyle="rgba(103,215,255,.10)";ctx.lineWidth=1;ctx.beginPath();for(let i=0;i<=144;i++){const a=i/144*Math.PI*2,x=Math.cos(a)*radius,z=Math.sin(a)*radius,y=Math.sin(a)*radius*Math.sin(inc)*.72;const p=project(rotatePoint(x,y,z));if(i===0)ctx.moveTo(p.x,p.y);else ctx.lineTo(p.x,p.y)}ctx.stroke();ctx.restore()}
  function drawNode(n){const c=colorFor(n.state);ctx.save();ctx.shadowColor=c.glow;ctx.shadowBlur=n.hover?24:12;const g=ctx.createRadialGradient(n.x-n.r*.3,n.y-n.r*.32,2,n.x,n.y,n.r);g.addColorStop(0,"rgba(120,229,255,.96)");g.addColorStop(.22,"rgba(24,91,118,.94)");g.addColorStop(1,"rgba(3,14,20,.99)");ctx.fillStyle=g;ctx.strokeStyle=c.edge;ctx.lineWidth=n.center?1.5:1.1;ctx.beginPath();ctx.arc(n.x,n.y,n.r,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.shadowBlur=0;ctx.textAlign="center";ctx.textBaseline="middle";ctx.fillStyle="#d7f2ff";ctx.font=`${n.center?"600 13px":"600 9px"} Segoe UI`;ctx.fillText(n.label.length>18?n.label.slice(0,16)+"…":n.label,n.x,n.y-3);ctx.fillStyle=n.state==="NORMAL"?"#65f2b0":c.edge;ctx.font="7px Segoe UI";ctx.fillText(n.sub||n.state,n.x,n.y+11);ctx.restore()}

  function orbitChildren(){
    if(centerEntity.kind==="firm") return data.desks;
    if(centerEntity.kind==="layer") return (centerEntity.childIds||[]).map(byId).filter(Boolean);
    const direct=childrenOf(centerEntity.id);
    if(direct.length) return direct.slice(0,6);
    if(centerEntity.layer===1) return data.deskSystems.map((name,i)=>({id:`${centerEntity.id}-${name}`,name,layer:"SYS",state:centerEntity.state,parentId:centerEntity.id,system:true,index:i}));
    return [];
  }

  function render(now){ctx.clearRect(0,0,W,H);hitNodes=[];const children=orbitChildren();const orbits=Math.max(1,Math.min(3,children.length));for(let i=0;i<orbits;i++)drawOrbit([190,215,235][i],[.32,-.44,.52][i]);const plotted=children.map((d,i)=>{const a=phases[i%6]+now*orbitSpeeds[i%6]*.001;const r=radii[i%6],inc=inclinations[i%6];const p=project(rotatePoint(Math.cos(a)*r,Math.sin(a)*r*Math.sin(inc)*.76,Math.sin(a)*r));return{kind:d.system?"system":"desk",id:d.id,label:d.name||d.id,state:d.state||"NORMAL",sub:d.system?"ACTIVE":`L${d.layer}`,entity:d,x:p.x,y:p.y,z:p.z,r:Math.max(20,29*p.scale)}});
    const center={kind:"center",id:centerEntity.id,label:centerEntity.kind==="firm"?"DUSTY CORE":centerEntity.name||centerEntity.id,state:centerEntity.state||"NORMAL",sub:centerEntity.kind==="firm"?"FIRM":centerEntity.layer!==undefined?`L${centerEntity.layer}`:"CENTER",entity:centerEntity,x:W/2,y:H/2,z:0,r:46,center:true};
    const all=[...plotted,center].sort((a,b)=>a.z-b.z);all.forEach(n=>{n.hover=hoverNode&&hoverNode.kind===n.kind&&hoverNode.id===n.id;drawNode(n);hitNodes.push(n)});requestAnimationFrame(render)}
  requestAnimationFrame(render);

  function renderLayerNav(){const nav=$("#layerNavigator");nav.innerHTML=`<small>HIERARCHY</small>${hierarchy.layers.map(l=>`<button data-layer="${l.layer}" class="${activeLayer===l.layer?"active":""}" title="${l.name}">L${l.layer}</button>`).join("")}`}
  function setFirmView(){activeLayer=1;centerEntity={kind:"firm",id:"FIRM",name:"Dusty Core",state:"NORMAL"};rotationY=-.12;rotationX=.10;$("#backToFirm").hidden=true;$("#focusLabel").textContent="FIRM / GENERALIST LAYER";updateDossier();renderLayerNav()}
  function setLayerView(layerNum,parentId=null){activeLayer=layerNum;const layer=hierarchy.layers.find(x=>x.layer===layerNum);if(!layer)return;if(layerNum===1){setFirmView();return}let entity={...layer,kind:"layer",state:"NORMAL"};if(layerNum===3&&parentId){const p=byId(parentId);if(p)entity={...p,kind:"desk"}}if(layerNum===4&&parentId){const p=byId(parentId);if(p)entity={...p,kind:"desk"}}centerEntity=entity;rotationY=-.08;rotationX=.12;$("#backToFirm").hidden=false;$("#focusLabel").textContent=entity.kind==="layer"?entity.name.toUpperCase():`${entity.name} / CHILDREN`;updateDossier();renderLayerNav()}

  function descend(entity){if(!entity)return;const next=childrenOf(entity.id);canvas.animate([{transform:"scale(1)",opacity:1},{transform:"scale(1.48)",opacity:.16}],{duration:420,easing:"cubic-bezier(.2,.75,.25,1)"}).onfinish=()=>{if(entity.layer===1){centerEntity={...entity,kind:"desk"};activeLayer=1}else if(entity.layer===2){centerEntity={...entity,kind:"desk"};activeLayer=3}else if(entity.layer===3){centerEntity={...entity,kind:"desk"};activeLayer=4}else{centerEntity={...entity,kind:"desk"};activeLayer=entity.layer||activeLayer}rotationY=-.08;rotationX=.10;$("#backToFirm").hidden=false;$("#focusLabel").textContent=next.length?`${entity.name} / ${next.length} CHILDREN`:`${entity.name} / DESK SYSTEM`;updateDossier();renderLayerNav();canvas.animate([{transform:"scale(.78)",opacity:.08},{transform:"scale(1)",opacity:1}],{duration:560,easing:"cubic-bezier(.2,.75,.25,1)"})}}

  function updateDossier(){const e=centerEntity;if(e.kind==="firm"){$("#deskDossier").innerHTML=[metric("FIRM",data.firm.state,"center click for detailed firm view"),metric("L1","6 GENERALISTS","independent capital"),metric("MTD",pct(data.firm.pnlMonthPct),"firm aggregate"),metric("RISK",`${data.firm.openRiskPct.toFixed(2)}%`,"open risk")].join("");return}if(e.kind==="layer"){$("#deskDossier").innerHTML=[metric("LAYER",`L${e.layer}`,e.name),metric("DESKS",String(e.childIds.length),"seeded hierarchy"),metric("STATE","NORMAL","UI-lab aggregate"),metric("ACTION","CLICK ORB","descend into desk")].join("");return}$("#deskDossier").innerHTML=[metric("EQUITY",money(e.equity),e.broker||"desk capital"),metric("TODAY",pct(e.today),e.accountType||"mock"),metric("MTD",pct(e.mtd),`PF ${Number(e.pf||0).toFixed(2)} · Sharpe ${Number(e.sharpe||0).toFixed(2)}`),metric("RISK / DD",`${Number(e.risk||0).toFixed(2)}% / ${Number(e.dd||0).toFixed(2)}%`,e.state||"NORMAL")].join("")}

  function hitAt(x,y){return [...hitNodes].reverse().find(n=>Math.hypot(x-n.x,y-n.y)<=n.r)}
  canvas.addEventListener("pointerdown",e=>{if($("#floorDetail").hidden===false)return;dragging=true;dragMoved=false;lastX=e.clientX;lastY=e.clientY;viewport.classList.add("dragging");canvas.setPointerCapture(e.pointerId)});
  canvas.addEventListener("pointermove",e=>{const r=canvas.getBoundingClientRect(),x=e.clientX-r.left,y=e.clientY-r.top;hoverNode=hitAt(x,y)||null;if(dragging){const dx=e.clientX-lastX,dy=e.clientY-lastY;if(Math.abs(dx)+Math.abs(dy)>2)dragMoved=true;rotationY+=dx*.006;rotationX=Math.max(-.65,Math.min(.65,rotationX+dy*.004));lastX=e.clientX;lastY=e.clientY}});
  canvas.addEventListener("pointerup",e=>{viewport.classList.remove("dragging");if(!dragMoved){const r=canvas.getBoundingClientRect(),n=hitAt(e.clientX-r.left,e.clientY-r.top);if(n){if(n.kind==="center")openDetails();else if(n.kind==="desk"&&!n.entity.system)descend(n.entity)}}dragging=false});
  canvas.addEventListener("pointerleave",()=>{hoverNode=null});

  function curveBars(seed){return Array.from({length:22},(_,i)=>`<span style="height:${24+((i*17+seed*13)%61)}%"></span>`).join("")}
  function hierarchySummary(){return hierarchy.layers.map(l=>`<div><span>L${l.layer}</span><b>${l.childIds.length} DESKS</b><span>${l.name.replace(/^Layer \d+ — /,"")}</span></div>`).join("")}
  function entityType(e){if(e.kind==="firm")return"Firm Aggregate";if(e.kind==="layer")return"Layer Aggregate";if(e.layer===0)return"Demo Proof Desk";if(e.layer===1)return"Generalist Desk";if(e.layer===2)return"Style Specialist Desk";if(e.layer===3)return"Sector Specialist Desk";if(e.layer===4)return"Symbol Specialist Desk";return"Trading Desk"}
  function recentFor(e){if(e.kind==="firm"||e.kind==="layer")return data.positions;return data.positions.filter(p=>p.desk===e.id).length?data.positions.filter(p=>p.desk===e.id):data.positions.slice(0,4)}
  function childRoster(e){const kids=e.kind==="firm"?data.desks:e.kind==="layer"?(e.childIds||[]).map(byId).filter(Boolean):childrenOf(e.id);if(!kids.length)return"<p>No deeper seeded trading-desk layer beneath this node. Operational subsystems remain available from the desk runtime.</p>";return `<div class="child-roster">${kids.slice(0,18).map(k=>`<div class="child-row"><b>${k.id}</b><span>${k.name||k.id}</span><span>${k.broker||"—"}</span><span>${k.accountType||"—"}</span><span class="state-${k.state||"NORMAL"}">${k.state||"NORMAL"}</span></div>`).join("")}</div>`}
  function openDetails(){const e=centerEntity;const isFirm=e.kind==="firm";const balance=isFirm?data.firm.balance:Number(e.equity||0)+37.42;const equity=isFirm?data.firm.equity:Number(e.equity||0);const mtd=isFirm?data.firm.pnlMonthPct:Number(e.mtd||2.3);const dd=isFirm?data.firm.drawdownPct:Number(e.dd||1.2);const pf=isFirm?1.71:Number(e.pf||1.48);const sharpe=isFirm?1.36:Number(e.sharpe||1.08);const recent=recentFor(e);$("#detailIdentity").textContent=isFirm?"DUSTY DRAGON / FIRM PERFORMANCE":`${e.id} / ACCOUNT PERFORMANCE`;$("#detailContent").innerHTML=`<div class="account-hero"><section class="account-identity"><h2>${isFirm?"Dusty Dragon":e.name||e.id}</h2><div class="parent-trail">${isFirm?"FIRM ROOT":`L${e.layer??"—"} · ${e.parentId||"FIRM"}`}</div><p>Type: ${entityType(e)}</p><p>Broker: ${e.broker||"Multiple broker accounts"}</p><p>Account Type: ${e.accountType||"Multiple MT5 account types"}</p><p>Environment: ${e.environment||"MIXED / UI LAB"}</p><div class="identity-separator"></div><p>State: <b class="state-${e.state||"NORMAL"}">${e.state||data.firm.state}</b></p><p>Account Alias: ${e.accountAlias||"Firm aggregate"}</p><p>MT5 Server: ${e.server||"Multiple"}</p></section><section class="account-performance"><table><thead><tr><th>Performance</th><th>Return</th><th>Profit</th><th>Trades</th></tr></thead><tbody><tr><td>Today</td><td>${pct(e.today||.62)}</td><td>${money(equity*(e.today||.62)/100)}</td><td>3</td></tr><tr><td>This Week</td><td>${pct(mtd*.42)}</td><td>${money(equity*mtd*.0042)}</td><td>14</td></tr><tr><td>This Month</td><td>${pct(mtd)}</td><td>${money(equity*mtd/100)}</td><td>31</td></tr><tr><td>All Time</td><td>${pct(mtd*2.7)}</td><td>${money(equity*.118)}</td><td>117</td></tr></tbody></table></section><section class="account-curves"><small>RETURN BY TRADE</small><div class="mini-curve">${curveBars(Number(String(e.id||7).replace(/\D/g,"").slice(-2))||7)}</div><small>BALANCE / EQUITY PATH</small></section></div><div class="detail-grid"><section class="detail-panel"><h3>QUANT STATISTICS</h3><div class="stat-cloud">${[["Balance",money(balance)],["Equity",money(equity)],["Profit Factor",pf.toFixed(2)],["Sharpe",sharpe.toFixed(2)],["Sortino",(sharpe*1.38).toFixed(2)],["Drawdown",`${dd.toFixed(2)}%`],["Expectancy",`+${(.14+pf*.07).toFixed(2)}R`],["Win Rate",`${(51+pf*6).toFixed(1)}%`]].map(([a,b])=>`<div><span>${a}</span><b>${b}</b></div>`).join("")}</div></section><section class="detail-panel"><h3>RECENT / OPEN TRADES</h3><table class="detail-table"><thead><tr><th>Symbol</th><th>Side</th><th>P&L</th><th>R</th></tr></thead><tbody>${recent.map(p=>`<tr><td>${p.symbol}</td><td>${p.side}</td><td class="${p.pnl>=0?"positive":"negative"}">${money(p.pnl)}</td><td>${p.r.toFixed(2)}R</td></tr>`).join("")}</tbody></table></section><section class="detail-panel"><h3>HIERARCHY / CHILD DESKS</h3>${childRoster(e)}</section></div><div class="hierarchy-summary">${hierarchySummary()}</div>`;$("#floorDetail").hidden=false}

  $("#backToFirm").addEventListener("click",setFirmView);$("#closeDetail").addEventListener("click",()=>{$("#floorDetail").hidden=true});
  document.addEventListener("click",e=>{const layer=e.target.closest("[data-layer]");if(layer){const n=Number(layer.dataset.layer);if(n===3)setLayerView(3,"S01");else if(n===4)setLayerView(4,"L3-1-1");else setLayerView(n)}const m=e.target.closest("[data-matrix-desk]");if(m){const d=data.desks.find(x=>x.id===m.dataset.matrixDesk);if(d)descend(d)}const w=e.target.closest("[data-workspace]");if(w){document.querySelectorAll("[data-workspace]").forEach(b=>b.classList.toggle("active",b===w));document.querySelectorAll(".workspace").forEach(s=>s.classList.toggle("active",s.id===w.dataset.workspace))}const cmd=e.target.closest("[data-command]");if(cmd){pendingCommand=cmd.dataset.command;$("#dialogTitle").textContent=pendingCommand.replaceAll("_"," ");$("#dialogCopy").textContent="UI laboratory only. Confirming records a local mock audit event; no MT5 or broker path is touched.";$("#commandDialog").showModal()}});

  $("#watchlistTable").innerHTML=`<table class="data-table"><thead><tr><th>Symbol</th><th>Last</th><th>Move</th><th>Spread</th><th>Regime</th></tr></thead><tbody>${data.watchlist.map(x=>`<tr><td><b>${x.symbol}</b></td><td>${x.price}</td><td class="${x.move>=0?"positive":"negative"}">${pct(x.move)}</td><td>${x.spread}</td><td>${x.regime}</td></tr>`).join("")}</tbody></table>`;
  $("#decisionFeed").innerHTML=data.decisions.map(x=>`<div class="decision-item"><b><span>${x.time} · ${x.desk} · ${x.symbol}</span><span>${x.result}</span></b><p>Evidence score ${x.score}/100 · ${x.reason}</p></div>`).join("");
  $("#positionsTable").innerHTML=`<table class="data-table"><thead><tr><th>Desk / Symbol</th><th>Side</th><th>Entry</th><th>Mark</th><th>P&L</th><th>R</th><th>Risk</th><th>Age</th></tr></thead><tbody>${data.positions.map(x=>`<tr><td>${x.desk} · <b>${x.symbol}</b></td><td>${x.side}</td><td>${x.entry}</td><td>${x.mark}</td><td class="${x.pnl>=0?"positive":"negative"}">${money(x.pnl)}</td><td>${x.r.toFixed(2)}R</td><td>${x.risk.toFixed(2)}%</td><td>${x.age}</td></tr>`).join("")}</tbody></table>`;
  const heatClass=v=>v>.25?"positive-risk":v<-.25?"negative-risk":"neutral-risk";$("#riskHeatmap").innerHTML=data.riskHeatmap.map(x=>`<div class="heat-tile ${heatClass(x.value)}" style="grid-column:span ${Math.max(2,Math.round(x.size/3.2))};grid-row:span ${Math.max(2,Math.round(x.size/5))}" title="${x.label}: ${x.risk}% risk contribution"><small>${x.label}</small><strong>${x.symbol}</strong><span>${pct(x.value)}</span><small>RISK ${x.risk}%</small></div>`).join("");
  $("#riskStats").innerHTML=[kv("Portfolio open risk",`${data.riskStats.portfolioOpenRisk}%`),kv("Gross exposure",`${data.riskStats.grossExposure}%`),kv("Net exposure",`${data.riskStats.netExposure}%`),kv("USD contribution",`${data.riskStats.usdContribution}%`),kv("Max pair correlation",data.riskStats.maxPairCorrelation),kv("Simultaneous loss freq",`${data.riskStats.simultaneousLossFreq}%`),kv("VaR 95",`${data.riskStats.var95}%`),kv("Expected shortfall",`${data.riskStats.expectedShortfall}%`)].join("");
  const corr=[1,.44,.31,.18,.52,.22,.44,1,.28,.36,.81,.19,.31,.28,1,.41,.24,.33,.18,.36,.41,1,.37,.29,.52,.81,.24,.37,1,.43,.22,.19,.33,.29,.43,1];$("#correlationMatrix").innerHTML=corr.map(v=>`<div class="corr-cell" style="--a:${(.08+v*.42).toFixed(2)}">${v.toFixed(2)}</div>`).join("");
  $("#performanceStats").innerHTML=data.performance.stats.map(([l,v])=>`<div class="stat-block"><span>${l}</span><b>${v}</b></div>`).join("");$("#equityBars").innerHTML=data.performance.returns.map(v=>`<div class="equity-bar" style="height:${20+v*18}%"><span>${v.toFixed(1)}%</span></div>`).join("");$("#deskAttribution").innerHTML=data.performance.deskAttribution.map(x=>`<div class="attrib-row"><div class="attrib-head"><b>${x.id}</b><span>${money(x.pnl)} · ${x.pct}%</span></div><div class="bar-track"><div class="bar-fill" style="width:${x.pct*2.7}%"></div></div></div>`).join("");
  $("#researchQueue").innerHTML=data.researchQueue.map(x=>`<div class="research-item"><header><b>${x.id} · ${x.title}</b><span>${x.stage}</span></header><p>Impact ${x.impact} · ${x.progress}% complete</p><div class="progress"><span style="width:${x.progress}%"></span></div></div>`).join("");$("#evidenceList").innerHTML=data.evidence.map(x=>`<div class="evidence-item"><header><b>${x.state}</b><span>${x.confidence}% confidence</span></header><p>${x.claim}</p><small>${x.age} old</small></div>`).join("");$("#researchStats").innerHTML=[kv("Completed",data.research.completed),kv("Active",data.research.active),kv("Promoted",data.research.promoted),kv("Rejected",data.research.rejected),kv("Holdout",`${data.research.holdoutPass}/${data.research.holdoutTotal}`)].join("");
  const c=data.challenge;$("#challengeScore").innerHTML=`<div class="challenge-card"><h3>${c.target}</h3><div class="challenge-cols"><div><b>INCUMBENT</b>${kv("Return",pct(c.incumbent.ret))}${kv("DD",`${c.incumbent.dd}%`)}${kv("PF",c.incumbent.pf)}${kv("Sharpe",c.incumbent.sharpe)}</div><div><b>CHALLENGER</b>${kv("Return",pct(c.challenger.ret))}${kv("DD",`${c.challenger.dd}%`)}${kv("PF",c.challenger.pf)}${kv("Sharpe",c.challenger.sharpe)}</div></div><p>Day ${c.day}/${c.length} · Verdict: <b>${c.verdict}</b></p></div>`;
  $("#systemRows").innerHTML=`<div class="system-row head"><span>Component</span><span>State</span><span>Latency</span><span>CPU</span><span>RAM</span></div>${data.systems.map(x=>`<div class="system-row"><b>${x.name}</b><span class="state-${x.state}">${x.state}</span><span>${x.latency}</span><span>${x.cpu}%</span><span>${x.ram} MB</span></div>`).join("")}`;$("#auditRows").innerHTML=data.audit.map(([t,e,l])=>`<div class="audit-row"><time>${t}</time><span>${e}</span><span>${l}</span></div>`).join("");

  $("#confirmCommand").addEventListener("click",()=>{if(pendingCommand)$("#auditTail").textContent=`Audit: ${pendingCommand} mock-confirmed at ${new Date().toLocaleTimeString()}`;pendingCommand=null});
  function setMode(m){const a=m==="analytical";document.body.classList.toggle("analytical-mode",a);document.body.classList.toggle("spatial-mode",!a);$("#modeButton").textContent=a?"F3 SPATIAL":"F2 ANALYTICAL"}$("#modeButton").addEventListener("click",()=>setMode(document.body.classList.contains("analytical-mode")?"spatial":"analytical"));window.addEventListener("keydown",e=>{if(e.key==="F2"){e.preventDefault();setMode("analytical")}if(e.key==="F3"){e.preventDefault();setMode("spatial")}});
  function clock(){$("#clock").textContent=new Intl.DateTimeFormat("en-US",{hour:"2-digit",minute:"2-digit",second:"2-digit",hour12:false}).format(new Date())+" LOCAL"}clock();setInterval(clock,1000);
  setFirmView();
})();
